config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('calories/', include('calories.urls')),
    path('', include('pages.urls'))
]

pages/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    calorie_goal = models.DecimalField(max_digits=7, decimal_places=2, default=1000.0, blank=True)


calories/models.py
from django.db import models
from accounts.models import CustomUser

class foodItem(models.Model):
    name = models.CharField(max_length=200 ,null=False)
    calorie = models.DecimalField(max_digits=5, decimal_places=2, default=0, blank=True)
    person_of = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return str('{name} ({c} کالری)'.format(name=self.name, c=self.calorie))

class foodConsumed(models.Model):
    options = (
        ('صبحانه', 'صبحانه'),
        ('نهار', 'نهار'),
        ('شام', 'شام'),
    )

    name = models.ForeignKey(foodItem, on_delete=models.CASCADE)
    person_of = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(null=False,default=1)
    option = models.CharField(max_length=50, choices=options)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return str('{name} {op}'.format(name=self.name, op=self.options))

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-md-12">        
    <h1 style="margin-right: 20px;">درباره من</h1>
    <hr>
    <div class="row" style="margin: auto;">
        <div class="col-md-6">
            <div class="jumbotron">
                <h3 class="display-3" style="font-size: 2.5rem;">وبسایت کالری شمار روزانه</h3>
                <p class="lead">می‌توانید از طریق راه های ارتباطی با من در ارتباط باشید.</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card bg-light">
                <div class="card-header">راه های ارتباط</div>
                <div class="card-body">
                    <h4 class="card-title">ارتباط با من</h4>
                    <p class="card-text"><b>ایمیل :</b>info@arsalan.sc30@gmail.com</p>
                </div>
            </div>
        </div>
        
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<html>
<head>
    <title>کالری شمار</title>
    <!-- <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet"> -->
    <!-- <link href="https://fonts.cdnfonts.com/css/iranian-sans" rel="stylesheet"> -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.rawgit.com/rastikerdar/sahel-font/v1.0.0-alpha23/dist/font-face.css" rel="stylesheet" type="text/css" />
</head>
<body dir="rtl" style="font-family: Sahel,sans-serif;">
    <div class="container-xxxl">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark" data-bs-toggle="dark">
            <a class="navbar-brand" href="{% url 'home' %}">کالری شمار روزانه</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">خانه <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">درباره من</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">حساب شما</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fooditem_list' %}">غذا ها</a>
                        </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                    <div class="my-2 my-lg-0">
                        <a class="btn btn-hover color-5 ml-sm-2" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> خروج از حساب</a>
                        <a class="btn btn-hover color-5 my-2 my-sm-0" href="{% url 'profile' %}"><i class="fa fa-user"></i> سلام {{ user.username }}!</a>
                        <a href="{% url 'password_change' %}" class="btn btn-warning" style="margin-right: 10px;">تغییر کلمه عبور</a>
                    </div>
                {% else %}
                    <div class="my-2 my-lg-0">
                        <a class="btn btn-hover color-5 ml-sm-2" href="{% url 'login' %}"><i class="fa fa-sign-in"></i> ورود</a>
                        <a class="btn btn-hover color-5 my-2 my-sm-0" href="{% url 'signup' %}"><i class="fa fa-user-plus"></i> ثبت نام</a>
                    </div>
                {% endif %}
            </div>
        </nav>
    </div>
        {% block content %}
        {% endblock content %}
    <div>
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top ml-3" dir="ltr">
            <p class="col-md-4 mb-0 text-muted">© 2023 Arsalan Khodadadi</p>
        </footer>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/caloriegoal_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 w-100">
    <div class="card shadow">
        <div class="card-body">
            <h2 class="text-center">تغییر کالری روزانه هدف</h2>
            <form method="post">
                {% csrf_token %}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger alert-dismissible fade show"> {{ error}}
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                <div id="div_id_calorie_goal" class="form-group"> 
                    <label for="id_calorie_goal" class="">کالری مصرفی روزانه هدف :</label> 
                    <div class=""> 
                        <input type="number" class="numberinput form-control" name="calorie_goal" value="0.0" step="1" id="id_calorie_goal"> 
                    </div> 
                </div>

                <button type="submit" class="btn btn-success mt-3">ثبت</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/food_consumed_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 w-100">
    <div class="card bg-light">
        <div class="card-header text-center"><h4><b>حذف وعده غذایی</b></h4></div>
        <div class="card-body">
            <h2><b>حذف وعده غذایی مصرف شده</b></h2>
            <form method="post">
                {% csrf_token %}
                <p>آیا از حذف {{ foodconsumed.name }} مطمئن هستید؟</p>
                <button class="btn btn-danger" type="submit">حذف</button>
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/food_consumed_new.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
<div class="container mt-5 w-100">
    <div class="card shadow">
        <div class="card-body">
            <h2 class="text-center">افزودن وعده غذایی جدید</h2>
            <form method="post">
                {% csrf_token %}
                {% if form.errors %}
                <ul>
                    <li style="color: red;">لطفا مقادیر را درست وارد نمایید!</li>
                </ul>
                {% endif %}
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">نام غذا:</label>
                    {{ form.name|add_class:"form-control mb-2" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.quantity.id_for_label }}">تعداد:</label>
                    {{ form.quantity|add_class:"form-control mb-2" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.option.id_for_label }}">وعده غذایی:</label>
                    {{ form.option|add_class:"form-control mb-2" }}
                </div>
                <select name="person_of" required="" id="id_person_of" hidden="True">
                    <option value="{{ user.id }}" selected="">
                        {{ user.username }}
                    </option>
                </select>   

                <button type="submit" class="btn btn-success mt-3">افزودن</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/food_item.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 w-100">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">
            <strong>{{ user.username }} عزیز، در اینجا میتوانید لیست غذا های خود را مشاهده کنید!</strong>
        </h4>
        میتوانید غذا های خود را تغییر و در صورت نیاز غذا های جدید به لیست اضافه کنید.
        در ضمن میتوانید از طریق منوی بالای صفحه و یا دکمه زیر وارد حساب کاربری خود شوید.
        <a href="{% url 'profile' %}" class="btn btn-dark mt-2">وارد شدن به حساب</a>
    </div>
    <div class="card bg-light">
        <div class="card-header text-center"><h4><b>غذا های شما</b></h4></div>
        <div class="card-body">
            <a href="{% url 'fooditem_new' %}" class="w-50 mt-2 mb-2 btn btn-success button1" style="background-color:#4ef18f;"><i class="bi bi-plus-square"></i>افرودن غذای جدید</a>
            <form method="get">
                <div class="form-control">
                    <h5>{{ myFilter.form }}</h5>
                    <button class="btn btn-info" type="submit">جستجو</button>
                </div>
            </form>
            <div class="table-responsive" style="height: 600px; overflow: auto;">
                <table class="table table-striped table-hover">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col">نام غذا</th>
                            <th scope="col">کالری</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for foodItem in foodItemList %}
                            <tr class="table-info">
                                <td>{{ foodItem.name }}</td>
                                <td>{{ foodItem.calorie }}</td>
                                <td>
                                    <form method="post">
                                        {% csrf_token %}
                                        <a href="{% url 'fooditem_edit' foodItem.pk %}" class="btn btn-warning"><i class="fa fa-refresh"></i> بروزرسانی</a>
                                    </form>
                                </td>
                                <td>
                                    <form method="post">
                                        {% csrf_token %}
                                        <a href="{% url 'fooditem_delete' foodItem.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i> حذف</a>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/food_item_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 w-100">
    <div class="card bg-light">
        <div class="card-header text-center"><h4><b>حذف غذا</b></h4></div>
        <div class="card-body">
            <h2><b>حذف غذا</b></h2>
            <form method="post">
                {% csrf_token %}
                <p>آیا از حذف {{ foodItem.name }} مطمئن هستید؟</p>
                <button class="btn btn-danger" type="submit">حذف</button>
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/food_item_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 w-100">
    <div class="card shadow">
        <div class="card-body">
            <h2 class="text-center">بروزرسانی غذا</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_div }}
                
                <button type="submit" class="btn btn-success mt-3">ثبت</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/food_item_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container mt-5 w-100">
    <div class="card shadow">
        <div class="card-body">
            <h2 class="text-center">افزودن غذای جدید</h2>
            <form method="post">
                {% csrf_token %}
                {% if form.errors %}
                <ul>
                    <li style="color: red;">لطفا مقادیر را درست وارد نمایید!</li>
                </ul>
                {% endif %}
                <select name="person_of" required id="id_person_of" hidden="True">
                    <option value="{{user.id}}" selected>{{user.username}}</option>
                </select>
                <div id="div_id_name" class="form-group">
                    <label for="id_name" class="requiredField">
                        نام غذا<span class="asteriskField">*</span></label>
                    <div class="">
                        <input type="text" name="name" maxlength="200" autofocus="" class="textinput textInput form-control" required id="id_name"> 
                    </div> 
                </div> 
                <div id="div_id_calorie" class="form-group"> 
                    <label for="id_calorie" class="">مقدار کالری:</label> 
                    <div class=""> 
                        <input type="number" class="numberinput form-control" name="calorie" value="100.0" step="1" id="id_calorie"> 
                    </div> 
                </div>

                <button type="submit" class="btn btn-success mt-3">ثبت</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-auto">
    <div class="row mt-lg-5">
        <div class="col-xl-6 col-lg-6 col-md-6 mt-lg-5" style="border: 1px hidden gray;">
            <h2 class="p-2">کالری شمار روزانه</h2>
            <p class="p-2">با کالری شمار روزانه، مقدار کالری مصرفی روزانه خود را محاسبه و مدیریت کنید و با استفاده از آن به وضعیت ایده آل بدنی خود دست یابید.</p>
            <a href="{% url 'fooditem_list' %}" type="button" class="herobtn btn btn-lg px-4 me-md-2 btn-success">بزن بریم!</a>
        </div>
        <div class="col-xl-6 col-lg-6 col-md-6 mt-lg-5" style="border: 1px hidden gray;">
            <img src="{% static 'images/heart-healthy-diet.jpg' %}" alt="healthy-diet" class="img-fluid">
        </div>
    </div>
</div>
{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 w-100">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">
            <strong>{{ user.username }} عزیز، به حساب کاربری خود خوش آمدید!</strong>
        </h4>
        میتوانید در این صفحه مقدار کالری مصرفی خود را مدیریت کنید و غذا های مصرفی خود را اضافه کنید.
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="card bg-light" style="height: 300px;">
                <h5 class="card-header text-center"><b>مقدار کالری مصرفی شما در مقایسه با دیروز</b></h5>
                <div class="card-body">
                    <i class="fa fa-line-chart fa-4" aria-hidden="true"></i>
                    <h1 class="card-title pricing-card-title text-center">
                        <span dir="ltr">{{ calorie_compare }}</span><small class="text-muted fw-light">کالری</small>
                    </h1>
                    <p class="pt-4 text-center">مقایسه کالری مصرفی امروز شما با دیروز</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card bg-light" style="height: 300px;">
                <h5 class="card-header text-center"><b>کل کالری امروز مصرف شده شما</b></h5>
                <div class="card-body">
                    <i class="fa fa-pie-chart"></i>
                    <h1 class="card-title pricing-card-title text-center">
                        {{ calorie_today }}<small class="text-muted fw-light">/{{ profile_goal }}</small>
                    </h1>
                    <div class="progress my-3 shadow-sm rounded-5 mt-lg-5" style="height: 2rem" dir="ltr">
                        <div class="progress-bar progress-bar-striped progress-bar-animated rounded-5  {% if goal_percent > 100 %}bg-danger{% else %}bg-success{% endif %}"
                                            role="progressbar"
                                            style="width: {{ goal_percent }}%"
                                            aria-valuenow="{{ calorie_today }}"
                                            aria-valuemin="0"
                                            aria-valuemax="{{ profile_goal }}">
                                            {{ goal_percent }}%
                        </div>
                    </div>
                    <div>
                    <a href="{% url 'caloriegoal_edit' %}" type="button" class="w-100 btn btn-primary"><i class="fas fa-edit"></i> تغییر کالری روزانه هدف</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card bg-light" style="height: 300px;">
                <h5 class="card-header text-center"><b>کل کالری مصرفی شما در هفته اخیر</b></h5>
                <div class="card-body">
                    <i class="fa fa-bar-chart fa-4"></i>
                    <h1 class="card-title pricing-card-title text-center">
                        {{ calorie_thisweek }}<small class="text-muted fw-light">کالری</small>
                    </h1>
                    <p class="pt-4 text-center">مجموع کالری غذا هایی که در این هفته مصرف کرده اید</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5 w-100">
    <div class="card bg-light">
        <div class="card-header text-center"><h4><b>غذا های مصرف شده امروز</b></h4></div>
        <div class="card-body">
            <a href="{% url 'foodconsumed_new' %}" class="w-50 mt-2 mb-2 btn btn-success button1" style="background-color:#4ef18f;"><i class="bi bi-plus-square"></i> افزودن وعده غذایی</a>
            <div class="table-responsive" style="height: 400px; overflow: auto;">
                <table class="table table-striped table-hover">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col">نام غذا</th>
                            <th scope="col">وعده غذایی</th>
                            <th scope="col">تعداد</th>
                            <th scope="col">تاریخ</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for foodConsumed in FoodConsumedList %}
                            <tr class="table-info">
                                <td>{{ foodConsumed.name }}</td>
                                <td>{{ foodConsumed.option }}</td>
                                <td>{{ foodConsumed.quantity }}</td>
                                <td>{{ foodConsumed.date }}</td>
                                <td>
                                    <form method="post">
                                        {% csrf_token %}
                                        <a href="{% url 'foodconsumed_delete' foodConsumed.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i>حذف</a>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5 w-100">
    <div class="card bg-light">
        <div class="card-header text-center"><h4><b>غذا های مصرف شده به تفکیک تاریخ در این هفته</b></h4></div>
        <div class="card-body">
                <table class="table table-striped table-hover">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col">تاریخ</th>
                            <th scope="col">نام غذا</th>
                            <th scope="col">وعده غذایی</th>
                            <th scope="col">تعداد</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for record in records %}
                            <tr>
                                <td>{{ record.date }}</td>
                                <td>{{ record.name }}</td>
                                <td>{{ record.option }}</td>
                                <td>{{ record.quantity }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}